### ISSUE TITLE
Non-restrictive license on the horizon?

### ISSUE THREAD

**Issue by communityus** [SamVanheer/AngelscriptIDE#2]
Hi again Sam V.,

I commented a while back on the HL and SharpLife code, asking for best place to start. As you say, we don't know if Steam will ever budge, so best to start with something not licensed to Valve. I found another good project XLEngine that makes use of Angelscript I figured I can still start learning your code base (interested in the enterprise style) while still building a product. My hope was to include your AngelscriptIDE in with my games release on Steam as a tool or something. So wanted to clear up the license you had in mind for your code here if any.

Thanks for your work on your projects.

**Comment by SamVanheer** [comment]
I've added the MIT license, so you should be free to use this repository as you see fit.
